### ISSUE TITLE
New Dust II update broke the app

### ISSUE THREAD

**Issue by jbruses** [LuckeLucky/cs-round-parser#3]
Hello! Sorry to bother you. The new Dust II update has broken the application. When I want to open a demo, it opens and closes quickly.
Greetings! Thank you very much for doing the application, it is very useful!

**Comment by LuckeLucky** [comment]
Hi, try using https://github.com/LuckeLucky/cs-round-parser/releases/tag/v4.0.3.

**Comment by LuckeLucky** [comment]
Try the new versions.
